### ISSUE TITLE
'Download as PDF' not work

### ISSUE THREAD

**Issue by dieg00uy** [documize/community#193]
I am testing the community version and the functionality "Download as PDF" does not work. I looked on all the logs (documize, conversion, browser) but nothing.

My environment:
**SO**: Linux
**Version**: documize-community-linux-amd64 v2.0.1 (I also tried v2.0.0 and it also happens).
**Conversion Server**: I tried with https://api.documize.com and with local version (https://hub.docker.com/r/documize/conversion)

The import works OK in all my environments. The same happens with the export to HTML; it works without problems.

Is it a limitation of the CE or a bug? Look in all the documentation and i did not find anything about this.

Thank you!

**Comment by infotec-dehmer** [comment]
I have the same problem with the version hosted directly on documize.com

**Comment by mcmatts** [comment]
We're looking into this issue.

**Comment by HarveyKandola** [comment]
@dieg00uy 

Try Docker pulling v2.2.0 as have made a few tweaks in a bid to isolate the issue. Report back what happens!

@infotec-dehmer yup, we see the same, should be resolved shortly.

**Comment by dieg00uy** [comment]
Hi @HarveyKandola;
I just tried the updated docker and still happening :(
I am using this https://hub.docker.com/r/rusbaron/documize, is it the correct image or do you use another one?

Thanks!

**Comment by HarveyKandola** [comment]
@dieg00uy 

For the conversion service Docker container use this: https://hub.docker.com/r/documize/conversion

**Comment by dieg00uy** [comment]
Thanks for the quick reply @HarveyKandola 

I tried the new conversion 2.2.0 and the problem is still present.
If I consult log ("docker logs -f documize_conversion") I don't see anything when I export to PDF, however when I import a Word document I can see in the log information about the conversion.

**Comment by dieg00uy** [comment]
Done @HarveyKandola  ... and it's still not working :(

These are the steps I did:

1. Update the image: docker pull documize / conversion: 2.2.0
2. Remove my container: docker rm documize_conversion
3. Start my container again: docker-compose up -d
4. Looking at the logs (docker logs -f documize_conversion), I tried again the option "Download as PDF" and nothing happens.

**Comment by HarveyKandola** [comment]
@dieg00uy thanks for letting us know.

Do you ever get a PDF? None, sometimes, to start with?

**Comment by dieg00uy** [comment]
Thanks @HarveyKandola 
It never worked for me. First I started trying Documize installing this with a docker image, when I detected this problem I did a normal installation (linux) and I could verify that the problem also happened.
I'm evaluating the tool to start using it in the company where I work (in my team, around 15 developers) and really this feature of exporting to PDF is one of what we need to replace the current documentation.

PS: The tool is really very good, I will definitely recommend it, congratulations for the good work!

**Comment by HarveyKandola** [comment]
@dieg00uy 

What is your Conversion Service URL under Settings // General ?

**Comment by HarveyKandola** [comment]
Thanks @dieg00uy 

Just checking, but it is also recommended that Docker be given the IP address of your DNS server to help with domain name resolution (note the --dns switch):

docker run -d --name="documize-conversion" -p 8080:80 --dns=DNS_SERVER_IP documize/conversion:2.2.0

If that does not work, drop support team an email and someone will assist you to a resolution.

**Comment by dieg00uy** [comment]
@HarveyKandola 

I just tried using the parameter for DNS and nothing changed.
I sent an email to the support to continue the topic there, thank you for the help and the quick response.
