### ISSUE TITLE
[Bug Report] Email Setup GUI will not take inputs from form-fields

### ISSUE THREAD

**Issue by koshia** [documize/community#303]
This occurs on https://docs.domain.tld/settings/smtp page. When configuring SMTP settings by filling out the input fields, once Save & Test is clicked - the mouse cursor focus is reverted to the first field HOST setting. Cannot submit and commit settings.

This occurs on Chrome 75 and Firefox 67.

**Comment by HarveyKandola** [comment]
Which version are you running?

**Comment by koshia** [comment]
Version 3.10. I've had this issue since version 2.x. I didn't see anything in v3.11 that would fix or applies to this capability and is why I haven't updated binary to latest, yet.

**Comment by HarveyKandola** [comment]
v3.1.1 should fix it depending upon your DB provider.

**Comment by koshia** [comment]
> v3.1.1 should fix it depending upon your DB provider.

My DB Provider is MariaDB, latest. I've also upgraded to latest binary 3.12.  Still no go.  You can enter data on the form fields, but when you hit "Save & Test" at the end of the page, all it does is take you to the top to fill in host address again.

**Comment by HarveyKandola** [comment]
We are unable to reproduce with MariaDB latest running Documize 3.1.2 -- can you send screenshot to supportATdocumizeDOTcom
