### ISSUE TITLE
Unable to create Space in non-english language (folder_slug is empty)

### ISSUE THREAD

**Issue by demkinmaxim** [documize/community#85]
Hello!
Just a fresh install of Documize. I've tried to create my first space, and called it 'Общее' - all cyrillic letters. My MySQL database is in UTF, and I can see /api/folders request works correctly.
But I get JS error because folder_slug is empty.
https://i.imgur.com/Y7a4hiB.png

When I went to DB and changed the label.label manually to english name, everything is working fine now.

So, I can not use non-english language at all :(

**Comment by HarveyKandola** [comment]
Thanks for the report -- we will fix for next release, due at the end of this week!

**Comment by HarveyKandola** [comment]
Fixed for next release.

**Comment by HarveyKandola** [comment]
@demkinmaxim get v0.44 release for bug fix!

**Comment by qins** [comment]
On  documize online, I still cannot create chinese space name.

**Comment by HarveyKandola** [comment]
@qins we will check and report back ASAP

**Comment by sauls8t** [comment]
@qins resolved this issue with latest commits.

@HarveyKandola will push up release shortly and refresh cloud instances.

**Comment by qins** [comment]
**Awesome!**
@HarveyKandola @sauls8t

**Comment by HarveyKandola** [comment]
@qins deployed live -- please verify.

Will release self-host binaries next week!

**Comment by qins** [comment]
@HarveyKandola Problem solved! Thank you!
